"use client"

/**
 * AI Templates Section
 * @description Unified AI template section with grid/list views, category filter
 * pills, and Framer Motion animations. Merges hardcoded templates from
 * AI_TEMPLATE_CATEGORIES with dynamically generated templates from the database.
 * @module components/features/template-library/ai-templates-section
 */

import * as React from "react"
import { motion } from "framer-motion"
import { IconSearch, IconSparkles, IconX } from "@tabler/icons-react"

import { cn } from "@/lib/utils"
import { Input } from "@/components/ui/input"

import { AI_TEMPLATE_CATEGORIES, getCategoryColor } from "./constants"
import { AITemplateCard, AITemplateRow } from "./ai-template-card"
import type { AITemplate, Template } from "./types"

/**
 * View mode for the AI templates display
 */
type ViewMode = "grid" | "list"

/**
 * Props for the AITemplatesSection component
 */
interface AITemplatesSectionProps {
  /** Callback when using an AI template to create a post */
  onUseAITemplate: (template: AITemplate) => void
  /** Callback when saving an AI template to the user's library */
  onSaveAITemplate: (template: AITemplate) => void
  /** AI-generated templates from the database (auto-generated by the cron) */
  dynamicTemplates?: Template[]
  /** Current view mode from the parent (grid or list) */
  viewMode?: ViewMode
}

/**
 * Builds a flat list of all AI templates by merging hardcoded + dynamic.
 * @param dynamicTemplates - AI-generated templates from the database
 * @returns Flat array of AITemplate objects
 */
function buildAllAITemplates(dynamicTemplates: Template[]): AITemplate[] {
  const templates: AITemplate[] = []
  const seenIds = new Set<string>()

  // Hardcoded templates
  for (const group of AI_TEMPLATE_CATEGORIES) {
    for (const t of group.templates) {
      if (!seenIds.has(t.id)) {
        templates.push(t)
        seenIds.add(t.id)
      }
    }
  }

  // Dynamic DB templates
  for (const t of dynamicTemplates) {
    if (!seenIds.has(t.id)) {
      templates.push({
        id: t.id,
        name: t.name,
        content: t.content,
        category: t.category,
        tags: t.tags,
      })
      seenIds.add(t.id)
    }
  }

  return templates
}

/**
 * Unified AI template section with grid/list views, search, and category filter pills.
 *
 * @param props - Component props
 * @returns Section with category pills and AI template cards/rows
 */
export function AITemplatesSection({
  onUseAITemplate,
  onSaveAITemplate,
  dynamicTemplates = [],
  viewMode = "grid",
}: AITemplatesSectionProps) {
  const [activeCategory, setActiveCategory] = React.useState<string>("all")
  const [searchQuery, setSearchQuery] = React.useState("")

  /** All AI templates (hardcoded + dynamic) */
  const allTemplates = React.useMemo(
    () => buildAllAITemplates(dynamicTemplates),
    [dynamicTemplates]
  )

  /** Unique categories derived from templates */
  const categories = React.useMemo(() => {
    const catSet = new Set<string>()
    for (const t of allTemplates) catSet.add(t.category)
    return Array.from(catSet)
  }, [allTemplates])

  /** Category counts */
  const categoryCounts = React.useMemo(() => {
    const counts: Record<string, number> = { all: allTemplates.length }
    for (const t of allTemplates) {
      counts[t.category] = (counts[t.category] ?? 0) + 1
    }
    return counts
  }, [allTemplates])

  /** Filtered templates based on category + search */
  const filteredTemplates = React.useMemo(() => {
    let result = allTemplates

    if (activeCategory !== "all") {
      result = result.filter((t) => t.category === activeCategory)
    }

    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase()
      result = result.filter(
        (t) =>
          t.name.toLowerCase().includes(q) ||
          t.content.toLowerCase().includes(q) ||
          t.tags.some((tag) => tag.toLowerCase().includes(q))
      )
    }

    return result
  }, [allTemplates, activeCategory, searchQuery])

  return (
    <div className="flex flex-col gap-5">
      {/* Section header */}
      <div>
        <h2 className="text-lg font-bold tracking-tight">AI Templates</h2>
        <p className="text-xs text-muted-foreground mt-0.5">
          {allTemplates.length} pre-made templates to jumpstart your content
        </p>
      </div>

      {/* Search + category filter pills */}
      <div className="flex flex-col gap-2.5 sm:flex-row sm:items-center">
        {/* Search */}
        <div className="relative flex-1 max-w-xs">
          <IconSearch className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search AI templates..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-8 h-8 text-xs"
          />
          {searchQuery && (
            <button
              type="button"
              onClick={() => setSearchQuery("")}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
            >
              <IconX className="size-3" />
            </button>
          )}
        </div>

        {/* Category filter pills */}
        <div className="flex items-center gap-1 flex-wrap">
          <button
            type="button"
            onClick={() => setActiveCategory("all")}
            className={cn(
              "text-[11px] font-medium px-2.5 py-1 rounded-full transition-all",
              activeCategory === "all"
                ? "bg-foreground text-background"
                : "bg-muted text-muted-foreground hover:text-foreground"
            )}
          >
            All
            <span className="ml-1 opacity-70">{categoryCounts.all}</span>
          </button>

          {categories.map((cat) => {
            const isActive = activeCategory === cat
            const colors = getCategoryColor(cat)
            return (
              <button
                key={cat}
                type="button"
                onClick={() => setActiveCategory(cat)}
                className={cn(
                  "text-[11px] font-medium px-2.5 py-1 rounded-full transition-all",
                  isActive
                    ? colors.filterActive
                    : "bg-muted text-muted-foreground hover:text-foreground"
                )}
              >
                {cat}
                {(categoryCounts[cat] ?? 0) > 0 && (
                  <span className="ml-1 opacity-70">{categoryCounts[cat]}</span>
                )}
              </button>
            )
          })}
        </div>
      </div>

      {/* Empty search state */}
      {filteredTemplates.length === 0 && (
        <motion.div
          className="flex flex-col items-center justify-center py-12 px-4 text-center"
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          <div className="rounded-2xl bg-muted/50 p-5 mb-4">
            <IconSparkles className="h-10 w-10 text-muted-foreground/40" />
          </div>
          <h3 className="text-base font-semibold mb-1">No matching AI templates</h3>
          <p className="text-sm text-muted-foreground max-w-sm">
            Try adjusting your search or filter.
          </p>
        </motion.div>
      )}

      {/* Grid view */}
      {filteredTemplates.length > 0 && viewMode === "grid" && (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredTemplates.map((template, idx) => (
            <motion.div
              key={template.id}
              initial={{ opacity: 0, y: 12 }}
              animate={{
                opacity: 1,
                y: 0,
                transition: { duration: 0.25, delay: idx * 0.03, ease: [0.16, 1, 0.3, 1] },
              }}
            >
              <AITemplateCard
                template={template}
                borderColor={getCategoryColor(template.category).border}
                onUse={onUseAITemplate}
                onSave={onSaveAITemplate}
              />
            </motion.div>
          ))}
        </div>
      )}

      {/* List view */}
      {filteredTemplates.length > 0 && viewMode === "list" && (
        <div className="flex flex-col gap-2">
          {filteredTemplates.map((template, idx) => (
            <motion.div
              key={template.id}
              initial={{ opacity: 0, x: -8 }}
              animate={{
                opacity: 1,
                x: 0,
                transition: { duration: 0.2, delay: idx * 0.02, ease: [0.16, 1, 0.3, 1] },
              }}
            >
              <AITemplateRow
                template={template}
                onUse={onUseAITemplate}
                onSave={onSaveAITemplate}
              />
            </motion.div>
          ))}
        </div>
      )}
    </div>
  )
}
